services:
  - type: web
    name: simple-messenger
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 1 --timeout 0 -b 0.0.0.0:$PORT app:app
    healthCheckPath: /healthz
